### ISSUE TITLE
[FEAT] Ignore Codeblock or specific folders

### ISSUE THREAD

**Issue by Quorafind** [der-tobi/obsidian-simple-mention#5]
Is it possible to ignore codeblock or specific folders?

**Comment by MarcelH20** [comment]
Hi, 
I tried your plugin in my environment. First it is super cool to have the ability to mention  someone on some notes etc. But I got the issue directly, because I write code snippets and ideas to my notes (e.g. annotations in java). Now I have several annotation mentions.. :D 

It would be nice if you can integrate this feature. 

```java
@Test
class MyClass {}
```

**Comment by der-tobi** [comment]
Maybe a setting option to exclude codeblocks? Or what would you prefer? Will look into this after fixing the performance issues.

**Comment by MarcelH20** [comment]
Hi, 

configuration options is always a good option. But I'm not sure what the default should be. From my developer view I can't think about a use-case where I use mentions within a code block. Maybe only the search result will be thereby inflated.

It depends on the solution whether you should tags within a code block to the search result, I guess.

What do you think?

**Comment by der-tobi** [comment]
Hi @MarcelH20 

Good points.

It also affects the suggestions and registering of mentions. I don't think I would want @Test in my suggestions list, nor should the list appear when writing within a code block.
So my first gut feeling for a simple solution is to exclude mentions in code blocks by default and make them available via configuration options.

**Comment by der-tobi** [comment]
Version 1.0.0 has just been released (https://github.com/der-tobi/obsidian-simple-mention/tree/1.0.0).
With this version you can now exclude certain directories from indexing. Furthermore, code blocks are ignored and the plugin now only indexes Markdown files.
