### ISSUE TITLE
Tags are also found in images

### ISSUE THREAD

**Issue by MarcelH20** [der-tobi/obsidian-simple-mention#6]
Hi, 

while I use your plugin I've found another issue with the mention tags. Not only in codeblocks (#5). It seems that the search logic is too general for tags. The search is applied everywhere also in binary images. 

Unfortunately this ended in some performance issue, so I have to disable the plugin until there is a solution. But you already work on the performance issues, right? 

<img width="1068" alt="issue-with-mentions" src="https://user-images.githubusercontent.com/43904024/198978664-49f0f83c-d5f4-41a6-bead-6e0624ee7a88.png">

**Comment by der-tobi** [comment]
Hello @MarcelH20 

Thank you for your feedback.
I have also noticed this and I will fix it.

Cheers

**Comment by peterkruty** [comment]
Great plugin, unfortunately also have this problem. It also causes some performance problems.

**Comment by mizmiller** [comment]
Hi, good work with this plugin, it is really helpful!
I was about to report the same problem, so +1 here :-)
Any update regarding the fix?

**Comment by der-tobi** [comment]
Version 1.0.0 has just been released (https://github.com/der-tobi/obsidian-simple-mention/tree/1.0.0) which fixes this bug by indexing Markdown files only.
