### ISSUE TITLE
Can't load local vault

### ISSUE THREAD

**Issue by wickkk119** [der-tobi/obsidian-simple-mention#7]
After I installed simple-mention, the local vault could not be loaded and the obsidian interface was stuck at the loading workspace screen. When I uninstall simple-mention, obsidian can load the repository normally.

obsidian version: v1.0.3
simple-mention: 0.1.0

**Comment by dtger** [comment]
Same issue, had a ton of plugins enabled, but this is the one that causes the "loading workspace" being stuck. there's also a notable delay in enabling the plugin as well, a bit of put luck if the toggle is "saved" to settings, or is set to disabled (even though the toggle is "on").

**Comment by der-tobi** [comment]
Hello
This seems to be the same problem as in #1.

**Comment by kraibse** [comment]
Seems to be have a severe and constant increase in RAM usage too.

**Comment by der-tobi** [comment]
Version 1.0.0 has just been released (https://github.com/der-tobi/obsidian-simple-mention/tree/1.0.0).
With this version the index is now persisted in the indexeddb.
The initial indexing may still take some time, but after that it should start much faster.
I am closing this for now. Let me know if there are any further problems with this.
